# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Sherah Smith
title: On Off Up Down
email: sherah@onoffupdown.com
description: User Experience Research
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onoffupdown.com" # the base hostname & protocol for your site
twitter_username: sherah
github_username:  sherah

# Build settings
markdown: kramdown
